apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-8
  region: us-east-1

managednodeGroups:
  - name: expense
    instanceTypes: ["m5.large","c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    spot: true